#!/usr/bin/env python3
import contextlib
import hashlib
import io
import json
import sys
import tempfile
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))

import knowledge.check as check_module  # noqa: E402
import wiki_ingest  # noqa: E402
from knowledge.artifacts import capture  # noqa: E402
from knowledge.check import (  # noqa: E402
    ARCHITECTURE_EXPECTED_EDGES,
    ARCHITECTURE_INITIALIZER_PATHS,
    ARCHITECTURE_MAX_EDGE_DEPTH,
    ARCHITECTURE_MODULE_PATHS,
    RULE_REGISTRY,
    CheckResult,
    _architecture_import_targets,
    _taxonomy_entity_slugs,
    check_target,
    contract_findings,
    generated_surface_findings,
    rule_coverage_findings,
)

TRANSCRIPT = ROOT / "tests" / "fixtures" / "contracts" / "canonical-transcript-v1.json"
CONCEPT = ROOT / "tests" / "fixtures" / "knowledge" / "valid-concept.md"
NOW = "2026-08-21T00:00:00+00:00"
FIXTURE_MANIFEST = (
    "raw/sources/video/fixture-video/"
    "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/manifest.json"
)


def test_overview_drift_is_index_coverage_rule():
    findings = generated_surface_findings(
        ("generated bytes differ: wiki/overview.md",)
    )

    assert findings[0]["rule_id"] == "VR-KP-018"
    assert findings[0]["path"] == "wiki/overview.md"


def _tree_hash(root: Path) -> str:
    digest = hashlib.sha256()
    for path in sorted(root.rglob("*")):
        if path.is_file():
            digest.update(str(path.relative_to(root)).encode())
            digest.update(path.read_bytes())
    return digest.hexdigest()


def _setup() -> tuple[tempfile.TemporaryDirectory, Path, Path, str]:
    temporary = tempfile.TemporaryDirectory()
    repo = Path(temporary.name)
    manifest = capture(
        TRANSCRIPT,
        source_type="video",
        source_id="fixture-video",
        primary_source="https://www.youtube.com/watch?v=fixture-video",
        media_type="application/json",
        created_at=NOW,
        raw_root=repo / "raw",
    ).manifest_path
    relative_manifest = str(manifest.resolve().relative_to(repo.resolve()))
    meta = repo / "_meta"
    meta.mkdir()
    (meta / "knowledge.schema.json").write_bytes(
        (ROOT / "_meta" / "knowledge.schema.json").read_bytes()
    )
    (meta / "taxonomy.md").write_text(
        "## Tag 목록\n\n"
        "- `architecture` (alias: `legacy-architecture`)\n\n"
        "## Entity 목록\n\n"
        "- `canonical-entity` (alias: `legacy-entity`)\n",
        encoding="utf-8",
    )
    target = repo / "wiki"
    (target / "staging").mkdir(parents=True)
    return temporary, repo, target, relative_manifest


def _write_concept(
    target: Path,
    page_id: str,
    manifest: str,
    relation_row: str = "",
    subdir: str = "staging",
) -> Path:
    text = CONCEPT.read_text(encoding="utf-8").replace(FIXTURE_MANIFEST, manifest)
    text = text.replace("title: Contract Fixture Concept", f"title: {page_id}")
    text = text.replace(
        "| broader | [[fixture-parent]] | direct outgoing edge |",
        relation_row,
    )
    path = target / subdir / f"{page_id}.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return path


def test_valid_target_has_separate_structural_and_semantic_verdicts():
    temporary, repo, target, manifest = _setup()
    try:
        _write_concept(target, "valid-concept", manifest)
        result = check_target(
            target, repo_root=repo, include_repository_contracts=False
        )
        assert result.structural_verdict == "PASS", result.findings
        assert result.semantic_review == "not-performed"
    finally:
        temporary.cleanup()


def test_check_target_reads_each_disk_page_once(monkeypatch: pytest.MonkeyPatch):
    temporary, repo, target, manifest = _setup()
    try:
        page = _write_concept(target, "single-snapshot", manifest)
        original_read_text = Path.read_text
        page_reads = 0

        def count_page_reads(path: Path, *args, **kwargs):
            nonlocal page_reads
            if path == page:
                page_reads += 1
            return original_read_text(path, *args, **kwargs)

        monkeypatch.setattr(Path, "read_text", count_page_reads)

        result = check_target(
            target, repo_root=repo, include_repository_contracts=False
        )

        assert result.structural_verdict == "PASS", result.findings
        assert page_reads == 1
    finally:
        temporary.cleanup()


def test_check_target_does_not_read_an_overridden_page(
    monkeypatch: pytest.MonkeyPatch,
):
    temporary, repo, target, manifest = _setup()
    try:
        page = _write_concept(target, "override-snapshot", manifest).resolve()
        target = target.resolve()
        source = page.read_text(encoding="utf-8")
        original_read_text = Path.read_text
        page_reads = 0

        def count_page_reads(path: Path, *args, **kwargs):
            nonlocal page_reads
            if path == page:
                page_reads += 1
            return original_read_text(path, *args, **kwargs)

        monkeypatch.setattr(Path, "read_text", count_page_reads)

        result = check_target(
            target,
            repo_root=repo,
            overrides={page: source},
            include_repository_contracts=False,
        )

        assert result.structural_verdict == "PASS", result.findings
        assert page_reads == 0
    finally:
        temporary.cleanup()


def test_check_target_reports_invalid_utf8_page_as_structural_failure():
    temporary, repo, target, _ = _setup()
    try:
        page = target / "staging" / "invalid-utf8.md"
        page.write_bytes(b"\xff\n")

        result = check_target(
            target, repo_root=repo, include_repository_contracts=False
        )

        assert result.structural_verdict == "FAIL"
        assert any(
            item["rule_id"] == "VR-KP-004"
            and Path(item["path"]) == page
            and "utf-8" in item["message"].lower()
            for item in result.findings
        )
    finally:
        temporary.cleanup()


def test_check_target_passes_repo_root_to_repository_contract_checks(
    monkeypatch: pytest.MonkeyPatch,
):
    temporary, repo, target, manifest = _setup()
    try:
        _write_concept(target, "repository-contract-root", manifest)
        observed: list[tuple[str, Path]] = []

        def record_contract(root: Path):
            observed.append(("contract", root))
            return []

        def record_coverage(*, repo_root: Path):
            observed.append(("coverage", repo_root))
            return []

        def record_architecture(root: Path):
            observed.append(("architecture", root))
            return []

        monkeypatch.setattr(check_module, "contract_findings", record_contract)
        monkeypatch.setattr(check_module, "rule_coverage_findings", record_coverage)
        monkeypatch.setattr(
            check_module, "architecture_findings", record_architecture
        )

        result = check_target(target, repo_root=repo)

        assert result.structural_verdict == "PASS", result.findings
        assert observed == [
            ("contract", repo),
            ("coverage", repo),
            ("architecture", repo),
        ]
    finally:
        temporary.cleanup()


def test_rule_coverage_reports_business_logic_read_errors(tmp_path: Path):
    findings = rule_coverage_findings(repo_root=tmp_path)

    assert any(
        finding["rule_id"] == "VR-KP-020"
        and "unavailable business logic" in finding["message"]
        for finding in findings
    )


def test_check_target_uses_requested_repository_document_schema():
    temporary, repo, target, manifest = _setup()
    try:
        _write_concept(target, "repo-schema", manifest)
        schema_path = repo / "_meta" / "knowledge.schema.json"
        schema = json.loads(schema_path.read_text(encoding="utf-8"))
        schema["$defs"]["Properties"]["required"].append("repo_only_field")
        schema_path.write_text(json.dumps(schema), encoding="utf-8")

        result = check_target(
            target, repo_root=repo, include_repository_contracts=False
        )

        assert result.structural_verdict == "FAIL"
        assert any("repo_only_field" in item["message"] for item in result.findings)
    finally:
        temporary.cleanup()


def test_all_and_changed_use_same_rules_and_findings():
    temporary, repo, target, manifest = _setup()
    try:
        page = _write_concept(target, "valid-concept", manifest)
        all_result = check_target(target, repo_root=repo, mode="all")
        changed_result = check_target(
            target, repo_root=repo, mode="changed", changed_paths=[page]
        )
        assert all_result.findings == changed_result.findings
    finally:
        temporary.cleanup()


def test_changed_mode_excludes_unrelated_finding_and_includes_direct_inbound():
    temporary, repo, target, manifest = _setup()
    try:
        changed = _write_concept(target, "changed-page", manifest)
        _write_concept(
            target,
            "inbound-page",
            manifest,
            "| related | [[changed-page]] | invalid owner on direct inbound edge |",
        )
        _write_concept(
            target,
            "unrelated-page",
            manifest,
            "| broader | [[missing-page]] | unrelated defect |",
        )
        result = check_target(
            target,
            repo_root=repo,
            mode="changed",
            changed_paths=[changed],
        )
        finding_paths = {Path(item["path"]).stem for item in result.findings}
        assert "unrelated-page" not in finding_paths
        assert "inbound-page" in finding_paths
    finally:
        temporary.cleanup()


def test_checker_is_no_write():
    temporary, repo, target, manifest = _setup()
    try:
        _write_concept(target, "valid-concept", manifest)
        before = _tree_hash(repo)
        check_target(target, repo_root=repo)
        assert _tree_hash(repo) == before
    finally:
        temporary.cleanup()


def test_broken_link_is_high_finding():
    temporary, repo, target, manifest = _setup()
    try:
        _write_concept(
            target,
            "valid-concept",
            manifest,
            "| broader | [[missing-page]] | direct outgoing edge |",
        )
        result = check_target(target, repo_root=repo)
        assert any(item["rule_id"] == "VR-KP-008" for item in result.findings)
        assert result.structural_verdict == "FAIL"
    finally:
        temporary.cleanup()


def test_duplicate_basename_is_rejected():
    temporary, repo, target, manifest = _setup()
    try:
        _write_concept(target, "duplicate-page", manifest, subdir="staging/a")
        _write_concept(target, "duplicate-page", manifest, subdir="staging/b")
        result = check_target(target, repo_root=repo)
        assert sum(item["rule_id"] == "VR-KP-007" for item in result.findings) == 2
    finally:
        temporary.cleanup()


def test_typed_relation_cycle_is_rejected():
    temporary, repo, target, manifest = _setup()
    try:
        _write_concept(target, "page-a", manifest, "| broader | [[page-b]] | edge |")
        _write_concept(target, "page-b", manifest, "| broader | [[page-a]] | edge |")
        result = check_target(target, repo_root=repo)
        assert sum(item["rule_id"] == "VR-KP-013" for item in result.findings) == 2
    finally:
        temporary.cleanup()


def test_related_edge_owner_is_lexicographically_smaller_page():
    temporary, repo, target, manifest = _setup()
    try:
        _write_concept(target, "page-a", manifest)
        _write_concept(target, "page-z", manifest, "| related | [[page-a]] | edge |")
        result = check_target(target, repo_root=repo)
        assert any(item["rule_id"] == "VR-KP-012" for item in result.findings)
    finally:
        temporary.cleanup()


def test_non_collection_page_under_collections_is_rejected():
    temporary, repo, target, manifest = _setup()
    try:
        _write_concept(target, "valid-concept", manifest, subdir="collections")
        result = check_target(target, repo_root=repo)
        assert any(item["rule_id"] == "VR-KP-014" for item in result.findings)
    finally:
        temporary.cleanup()


@pytest.mark.parametrize(
    "subdir",
    ("invalid/staging", ".hidden/domains/software-engineering", "staging/domains"),
)
def test_lifecycle_root_must_be_the_first_and_only_root_component(subdir: str):
    temporary, repo, target, manifest = _setup()
    try:
        (repo / "_meta" / "domains.yaml").write_text(
            "version: 1\ndomains:\n  software-engineering:\n"
            "    status: active\n    label: Software Engineering\n"
            "    source_roots: [development]\n",
            encoding="utf-8",
        )
        _write_concept(target, "invalid-lifecycle", manifest, subdir=subdir)

        result = check_target(target, repo_root=repo)

        assert any(item["rule_id"] == "VR-KP-014" for item in result.findings)
    finally:
        temporary.cleanup()


def test_lifecycle_path_remediation_uses_schema_owned_roots():
    temporary, repo, target, manifest = _setup()
    try:
        schema_path = repo / "_meta" / "knowledge.schema.json"
        schema = json.loads(schema_path.read_text(encoding="utf-8"))
        lifecycle_path = schema["$defs"]["LifecyclePath"]
        lifecycle_path["pattern"] = lifecycle_path["pattern"].replace(
            "staging|domains|collections|archive",
            "staging|domains|collections|archive|incubator",
        )
        schema_path.write_text(json.dumps(schema), encoding="utf-8")
        _write_concept(target, "invalid-lifecycle", manifest, subdir="outside")

        result = check_target(target, repo_root=repo)

        finding = next(
            item
            for item in result.findings
            if item["rule_id"] == "VR-KP-014"
            and item["message"] == "page path must identify exactly one lifecycle root"
        )
        assert finding["remediation"] == (
            "place the page under one of: "
            "staging, domains, collections, archive, incubator"
        )
    finally:
        temporary.cleanup()


@pytest.mark.parametrize(
    "mutation",
    ["missing", "properties-list", "properties-null", "properties-scalar"],
)
def test_lifecycle_schema_error_remediation_names_the_path_pattern_contract(
    mutation: str,
):
    temporary, repo, target, _manifest = _setup()
    try:
        schema_path = repo / "_meta" / "knowledge.schema.json"
        schema = json.loads(schema_path.read_text(encoding="utf-8"))
        if mutation == "missing":
            del schema["$defs"]["LifecyclePath"]
        else:
            schema["$defs"]["PageWrite"]["properties"] = {
                "properties-list": [],
                "properties-null": None,
                "properties-scalar": 1,
            }[mutation]
        schema_path.write_text(json.dumps(schema), encoding="utf-8")

        result = check_target(target, repo_root=repo)

        finding = next(
            item
            for item in result.findings
            if item["rule_id"] == "VR-KP-004" and item["subject_id"] == "schema"
        )
        assert finding["remediation"] == (
            "define one non-empty LifecyclePath and reference it from "
            "PageWrite source_path and target_path"
        )
    finally:
        temporary.cleanup()


def test_concept_lifecycle_accepts_staging_domain_and_archive_roots():
    temporary, repo, target, manifest = _setup()
    try:
        (repo / "_meta" / "domains.yaml").write_text(
            "version: 1\ndomains:\n  software-engineering:\n"
            "    status: active\n    label: Software Engineering\n"
            "    source_roots: [development]\n",
            encoding="utf-8",
        )
        _write_concept(target, "staging-concept", manifest, subdir="staging")
        _write_concept(
            target,
            "domain-concept",
            manifest,
            subdir="domains/software-engineering",
        )
        _write_concept(target, "archive-concept", manifest, subdir="archive")

        result = check_target(target, repo_root=repo)

        assert not any(item["rule_id"] == "VR-KP-014" for item in result.findings)
    finally:
        temporary.cleanup()


def test_empty_target_is_not_a_structural_pass():
    with tempfile.TemporaryDirectory() as directory:
        target = Path(directory) / "wiki"
        target.mkdir()
        result = check_target(target)
        assert result.structural_verdict == "FAIL"
        assert any(item["rule_id"] == "VR-KP-004" for item in result.findings)


def test_full_check_excludes_generated_root_pages_and_templates():
    temporary, repo, target, manifest = _setup()
    try:
        _write_concept(target, "valid-concept", manifest)
        for filename in ("index.md", "overview.md"):
            (target / filename).write_text("invalid generated page\n", encoding="utf-8")
        (target / "templates").mkdir()
        (target / "templates" / "invalid.md").write_text(
            "invalid template\n", encoding="utf-8"
        )
        result = check_target(
            target,
            repo_root=repo,
            mode="all",
            include_repository_contracts=False,
        )
        assert result.structural_verdict == "PASS", result.findings
        assert result.exclusions == (
            ".git",
            ".venv",
            "__pycache__",
            "index.md",
            "node_modules",
            "overview.md",
            "templates/**",
            "venv",
        )
    finally:
        temporary.cleanup()


def test_full_check_includes_hidden_canonical_markdown():
    temporary, repo, target, _ = _setup()
    try:
        hidden = target / ".active-hidden"
        hidden.mkdir()
        page = hidden / "broken.md"
        page.write_text("# Broken\n", encoding="utf-8")

        result = check_target(target, repo_root=repo, mode="all")

        assert result.structural_verdict == "FAIL"
        assert any(Path(item["path"]) == page for item in result.findings)
    finally:
        temporary.cleanup()


def test_taxonomy_rejects_unknown_and_alias_tags():
    temporary, repo, target, manifest = _setup()
    try:
        page = _write_concept(target, "valid-concept", manifest)
        original = page.read_text(encoding="utf-8")
        for tag, expected_severity in (
            ("not-in-taxonomy", "HIGH"),
            ("legacy-architecture", "MEDIUM"),
        ):
            candidate = original.replace("tags: [architecture]", f"tags: [{tag}]")
            page.write_text(candidate, encoding="utf-8")
            result = check_target(
                target, repo_root=repo, include_repository_contracts=False
            )
            taxonomy = [
                item for item in result.findings if item["rule_id"] == "VR-KP-023"
            ]
            assert len(taxonomy) == 1, result.findings
            assert taxonomy[0]["severity"] == expected_severity
            assert tag in taxonomy[0]["message"]
            assert result.structural_verdict == (
                "FAIL" if expected_severity == "HIGH" else "PASS"
            )
    finally:
        temporary.cleanup()


def test_taxonomy_checks_entity_pages_and_path_links_only():
    temporary, repo, target, manifest = _setup()
    try:
        alias_page = _write_concept(
            target,
            "legacy-entity",
            manifest,
            subdir="staging/entities",
        )
        link_page = _write_concept(target, "link-page", manifest)
        linked = link_page.read_text(encoding="utf-8").replace(
            "## Open Questions",
            "Unknown [[wiki/domains/test/entities/not-in-taxonomy]] and "
            "ordinary [[not-in-taxonomy]].\n\n## Open Questions",
        )
        link_page.write_text(linked, encoding="utf-8")
        result = check_target(target, repo_root=repo)
        taxonomy = [
            item for item in result.findings if item["rule_id"] == "VR-KP-023"
        ]
        assert any(
            Path(item["path"]) == alias_page
            and item["severity"] == "MEDIUM"
            and "legacy-entity" in item["message"]
            for item in taxonomy
        )
        assert sum("not-in-taxonomy" in item["message"] for item in taxonomy) == 1
    finally:
        temporary.cleanup()


def test_check_target_ignores_fenced_wikilinks_in_graph_and_taxonomy():
    temporary, repo, target, manifest = _setup()
    try:
        page = _write_concept(target, "fenced-link", manifest)
        source = page.read_text(encoding="utf-8").replace(
            "Definition body.",
            "Definition body.\n\n````markdown\n"
            "[[missing-page]]\n"
            "[[wiki/domains/test/entities/not-in-taxonomy]]\n"
            "````",
            1,
        )
        page.write_text(source, encoding="utf-8")

        result = check_target(
            target, repo_root=repo, include_repository_contracts=False
        )

        assert result.structural_verdict == "PASS", result.findings
        assert not any(
            finding["rule_id"] in {"VR-KP-008", "VR-KP-023"}
            for finding in result.findings
        )
    finally:
        temporary.cleanup()


@pytest.mark.parametrize("marker", ["`", "~"])
def test_taxonomy_links_ignore_content_until_a_long_enough_closing_fence(
    tmp_path: Path, marker: str
):
    text = "\n".join(
        (
            marker * 4,
            marker * 3,
            "[[wiki/domains/test/entities/not-in-taxonomy]]",
            marker * 4,
        )
    )

    assert _taxonomy_entity_slugs(tmp_path / "page.md", text) == []


def test_taxonomy_dotted_entity_aliases_point_to_kebab_canonical():
    temporary, repo, target, manifest = _setup()
    try:
        (repo / "_meta" / "taxonomy.md").write_text(
            "## Tag 목록\n\n- `architecture`\n\n"
            "## Entity 목록\n\n- `qwen-2-5` (alias: `qwen-2.5`, `qwen-2.0`)\n",
            encoding="utf-8",
        )
        link_page = _write_concept(target, "link-page", manifest)
        linked = link_page.read_text(encoding="utf-8").replace(
            "## Open Questions",
            "Canonical [[wiki/domains/ai/entities/qwen-2-5]] and "
            "[[wiki/domains/ai/entities/qwen-2-5.md]]; aliases "
            "[[wiki/domains/ai/entities/qwen-2.5]] and "
            "[[wiki/domains/ai/entities/qwen-2.0]].\n\n## Open Questions",
        )
        link_page.write_text(linked, encoding="utf-8")

        result = check_target(target, repo_root=repo)
        taxonomy = [
            item for item in result.findings if item["rule_id"] == "VR-KP-023"
        ]

        assert len(taxonomy) == 2, taxonomy
        assert all(item["severity"] == "MEDIUM" for item in taxonomy)
        assert any("qwen-2.0" in item["message"] for item in taxonomy)
        assert any("qwen-2.5" in item["message"] for item in taxonomy)
        assert all("qwen-2-5" in item["message"] for item in taxonomy)
    finally:
        temporary.cleanup()


def test_taxonomy_rule_is_active_and_executable():
    assert RULE_REGISTRY["VR-KP-023"] == ("active", "taxonomy-check")
    assert not any(
        finding["subject_id"] == "VR-KP-023"
        for finding in rule_coverage_findings()
    )


def test_p2_t5_validation_rules_are_active_and_executable():
    for rule_id in ("VR-KP-015", "VR-KP-016", "VR-KP-022"):
        assert RULE_REGISTRY[rule_id] == ("active", "page-command-contract")
    assert not any(
        finding["subject_id"] in {"VR-KP-015", "VR-KP-016", "VR-KP-022"}
        for finding in rule_coverage_findings()
    )


def test_p2_t6_generated_rules_are_active_and_executable():
    for rule_id, implementation in (
        ("VR-KP-017", "cli-generated-parity"),
        ("VR-KP-018", "cli-index-coverage"),
    ):
        assert RULE_REGISTRY[rule_id] == ("active", implementation)
        assert not any(
            finding["subject_id"] == rule_id for finding in rule_coverage_findings()
        )


def _run_check_cli(result: CheckResult, report: str) -> tuple[int, list[str]]:
    original_check_target = wiki_ingest.check_target
    original_generated_drift = wiki_ingest.generated_drift
    wiki_ingest.check_target = lambda *args, **kwargs: result
    wiki_ingest.generated_drift = lambda *args, **kwargs: ()
    try:
        output = io.StringIO()
        with contextlib.redirect_stdout(output):
            return_code = wiki_ingest.main(
                [
                    "check",
                    "--all",
                    "--target-root",
                    str(ROOT / "wiki"),
                    "--report",
                    report,
                ]
            )
    finally:
        wiki_ingest.check_target = original_check_target
        wiki_ingest.generated_drift = original_generated_drift
    return return_code, output.getvalue().splitlines()


def test_check_text_report_includes_exclusions():
    result = CheckResult(
        structural_verdict="PASS",
        semantic_review="not-performed",
        mode="all",
        exclusions=(".git", "templates/**"),
        findings=(),
    )

    return_code, output = _run_check_cli(result, "text")

    assert return_code == 0
    assert "exclusions=.git,templates/**" in output


def test_check_jsonl_report_includes_exclusions():
    result = CheckResult(
        structural_verdict="PASS",
        semantic_review="not-performed",
        mode="all",
        exclusions=(".git", "templates/**"),
        findings=(),
    )

    return_code, output = _run_check_cli(result, "jsonl")

    assert return_code == 0
    assert json.loads(output[-1])["result"]["exclusions"] == [
        ".git",
        "templates/**",
    ]


def test_architecture_check_includes_cli_entrypoint():
    from knowledge.check import architecture_findings

    with tempfile.TemporaryDirectory() as directory:
        repo = Path(directory)
        package = repo / "scripts" / "knowledge"
        package.mkdir(parents=True)
        (package / "__init__.py").write_text("", encoding="utf-8")
        (repo / "scripts" / "wiki_ingest.py").write_text(
            "import ytscript\n", encoding="utf-8"
        )
        findings = architecture_findings(repo)
        assert any("wiki_ingest -> ytscript" in item["message"] for item in findings)


def _copy_architecture_fixture(destination_root: Path) -> None:
    import shutil

    for relative in ARCHITECTURE_MODULE_PATHS.values():
        destination = destination_root / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(ROOT / relative, destination)
    for relative in ARCHITECTURE_INITIALIZER_PATHS:
        destination = destination_root / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(ROOT / relative, destination)


def test_architecture_check_rejects_acyclic_edge_outside_exact_contract(tmp_path: Path):
    from knowledge.check import architecture_findings

    _copy_architecture_fixture(tmp_path)
    materialize = tmp_path / "scripts/knowledge/materialize.py"
    materialize.write_text(
        materialize.read_text(encoding="utf-8") + "\nimport knowledge.graph\n",
        encoding="utf-8",
    )

    findings = architecture_findings(tmp_path)

    assert any(
        item["rule_id"] == "VR-KP-019"
        and "unexpected architecture edge" in item["message"]
        for item in findings
    )


def test_architecture_check_rejects_unregistered_module(tmp_path: Path):
    from knowledge.check import architecture_findings

    _copy_architecture_fixture(tmp_path)
    rogue = tmp_path / "scripts/knowledge/rogue.py"
    rogue.write_text("import knowledge.materialize\n", encoding="utf-8")

    findings = architecture_findings(tmp_path)

    assert any(
        item["rule_id"] == "VR-KP-019"
        and "unexpected architecture module" in item["message"]
        for item in findings
    )


@pytest.mark.parametrize(
    "statement",
    (
        "import knowledge.missing",
        "from knowledge.missing import leaf",
        "import scripts.contracts.missing",
        "import knowledge",
        "import contracts",
        "from knowledge import *",
        "from contracts import *",
        "import scripts.knowledge",
        "import scripts.contracts",
        "from scripts import knowledge",
        "from scripts import contracts",
        "import scripts",
        "from scripts import *",
        "import scripts.missing",
        "from scripts import missing",
        "import scripts.knowledge.check",
        "from scripts.knowledge import check",
        "import scripts.contracts.privacy",
        "from scripts.contracts import privacy",
    ),
)
def test_architecture_check_rejects_import_of_unregistered_local_module(
    tmp_path: Path, statement: str
):
    from knowledge.check import architecture_findings

    _copy_architecture_fixture(tmp_path)
    graph = tmp_path / "scripts/knowledge/graph.py"
    graph.write_text(
        graph.read_text(encoding="utf-8") + f"\n{statement}\n",
        encoding="utf-8",
    )

    findings = architecture_findings(tmp_path)

    assert any(
        item["rule_id"] == "VR-KP-019"
        and "unregistered architecture import" in item["message"]
        for item in findings
    )


def test_architecture_check_rejects_unregistered_local_package_import(tmp_path: Path):
    from knowledge.check import architecture_findings

    _copy_architecture_fixture(tmp_path)
    helpers = tmp_path / "scripts/helpers"
    helpers.mkdir()
    (helpers / "__init__.py").write_text("", encoding="utf-8")
    graph = tmp_path / "scripts/knowledge/graph.py"
    graph.write_text(
        graph.read_text(encoding="utf-8") + "\nimport helpers\n",
        encoding="utf-8",
    )

    findings = architecture_findings(tmp_path)

    assert any(
        item["rule_id"] == "VR-KP-019"
        and "forbidden repository import" in item["message"]
        for item in findings
    )


def test_architecture_module_identity_collision_is_deterministic(tmp_path: Path):
    from knowledge.check import architecture_findings

    _copy_architecture_fixture(tmp_path)
    collision = tmp_path / "scripts/knowledge/check"
    collision.mkdir()
    (collision / "__init__.py").write_text("", encoding="utf-8")

    first = architecture_findings(tmp_path)
    second = architecture_findings(tmp_path)

    assert first == second
    assert any(
        item["rule_id"] == "VR-KP-019"
        and "duplicate architecture module identity" in item["message"]
        for item in first
    )


@pytest.mark.parametrize(
    "statement",
    (
        "from knowledge import check",
        "from knowledge import check as checker",
        "from . import check",
    ),
)
def test_architecture_check_resolves_import_from_alias_cycles(
    tmp_path: Path, statement: str
):
    from knowledge.check import architecture_findings

    _copy_architecture_fixture(tmp_path)
    graph = tmp_path / "scripts/knowledge/graph.py"
    graph.write_text(
        graph.read_text(encoding="utf-8") + f"\n{statement}\n",
        encoding="utf-8",
    )

    findings = architecture_findings(tmp_path)

    assert any("import cycle detected" in item["message"] for item in findings)
    assert not any(
        "invalid relative architecture import" in item["message"]
        for item in findings
    )


@pytest.mark.parametrize(
    ("relative_path", "statement"),
    (
        ("scripts/knowledge/graph.py", "from .. import os"),
        ("scripts/knowledge/graph.py", "from ... import os"),
        ("scripts/contracts/timestamps.py", "from .. import os"),
        ("scripts/contracts/timestamps.py", "from ... import os"),
        ("scripts/wiki_ingest.py", "from . import os"),
    ),
)
def test_architecture_check_rejects_relative_import_beyond_package(
    tmp_path: Path, relative_path: str, statement: str
):
    from knowledge.check import architecture_findings

    _copy_architecture_fixture(tmp_path)
    source = tmp_path / relative_path
    source.write_text(
        source.read_text(encoding="utf-8") + f"\n{statement}\n",
        encoding="utf-8",
    )

    findings = architecture_findings(tmp_path)

    assert any(
        item["rule_id"] == "VR-KP-019"
        and "invalid relative architecture import" in item["message"]
        for item in findings
    )


def test_architecture_check_rejects_alternate_scripts_contract_import(tmp_path: Path):
    from knowledge.check import architecture_findings

    _copy_architecture_fixture(tmp_path)
    timestamps = tmp_path / "scripts/contracts/timestamps.py"
    timestamps.write_text(
        timestamps.read_text(encoding="utf-8")
        + "\nimport scripts.contracts.privacy\n",
        encoding="utf-8",
    )

    findings = architecture_findings(tmp_path)

    assert any(
        item["rule_id"] == "VR-KP-019"
        and item["message"]
        == "unregistered architecture import: contracts.timestamps -> scripts.contracts.privacy"
        for item in findings
    )


@pytest.mark.parametrize(
    ("payload", "mode"),
    ((b"def broken(:\n", "syntax"), (b"\xff\n", "encoding")),
)
def test_architecture_check_reports_unreadable_source(
    tmp_path: Path, payload: bytes, mode: str
):
    from knowledge.check import architecture_findings

    _copy_architecture_fixture(tmp_path)
    materialize = tmp_path / "scripts/knowledge/materialize.py"
    materialize.write_bytes(payload)

    findings = architecture_findings(tmp_path)

    assert any(
        item["rule_id"] == "VR-KP-019"
        and "unavailable architecture source" in item["message"]
        and mode in item["message"]
        for item in findings
    )


def test_architecture_check_reports_source_read_error(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
):
    from knowledge.check import architecture_findings

    _copy_architecture_fixture(tmp_path)
    materialize = tmp_path / "scripts/knowledge/materialize.py"
    original = Path.read_text

    def fail_selected(path: Path, *args, **kwargs):
        if path == materialize:
            raise OSError("fixture read failure")
        return original(path, *args, **kwargs)

    monkeypatch.setattr(Path, "read_text", fail_selected)

    findings = architecture_findings(tmp_path)

    assert any(
        item["rule_id"] == "VR-KP-019"
        and "unavailable architecture source" in item["message"]
        and "read" in item["message"]
        for item in findings
    )


def test_page_command_contract_reports_invalid_utf8_surface(tmp_path: Path):
    documents = tmp_path / "scripts" / "knowledge" / "documents.py"
    commands = tmp_path / "tests" / "test_page_commands.py"
    fs_tests = tmp_path / "tests" / "test_fs.py"
    for path in (documents, commands, fs_tests):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("", encoding="utf-8")
    documents.write_bytes(b"\xff\n")

    findings = check_module.page_command_contract_findings(tmp_path)

    assert any(
        item["rule_id"] == "VR-KP-020"
        and Path(item["path"]) == documents
        and "unavailable" in item["message"]
        for item in findings
    )


@pytest.mark.parametrize(
    ("package", "statement"),
    (
        ("knowledge", "from . import check\n"),
        ("contracts", "import ytscript\n"),
    ),
)
def test_architecture_check_rejects_package_initializer_imports(
    tmp_path: Path, package: str, statement: str
):
    from knowledge.check import architecture_findings

    _copy_architecture_fixture(tmp_path)
    initializer = tmp_path / "scripts" / package / "__init__.py"
    initializer.write_text(statement, encoding="utf-8")

    findings = architecture_findings(tmp_path)

    assert any(
        item["rule_id"] == "VR-KP-019"
        and "package initializer import" in item["message"]
        for item in findings
    )


def test_architecture_check_rejects_unregistered_nested_initializer(tmp_path: Path):
    from knowledge.check import architecture_findings

    _copy_architecture_fixture(tmp_path)
    initializer = tmp_path / "scripts/knowledge/rogue/__init__.py"
    initializer.parent.mkdir()
    initializer.write_text("from knowledge import check\n", encoding="utf-8")

    findings = architecture_findings(tmp_path)

    assert any(
        item["rule_id"] == "VR-KP-019"
        and "unexpected architecture module" in item["message"]
        and Path(item["path"]) == initializer
        for item in findings
    )


@pytest.mark.parametrize("failed_packages", (("knowledge",), ("knowledge", "contracts")))
def test_architecture_check_reports_inventory_errors(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    failed_packages: tuple[str, ...],
):
    import os

    from knowledge.check import architecture_findings

    _copy_architecture_fixture(tmp_path)
    original = os.walk
    failed_roots = {tmp_path / "scripts" / package for package in failed_packages}

    def fail_selected(path: Path, *args, **kwargs):
        if Path(path) in failed_roots:
            error = OSError("fixture inventory failure")
            error.filename = str(Path(path) / "blocked")
            kwargs["onerror"](error)
            return iter(())
        return original(path, *args, **kwargs)

    monkeypatch.setattr(os, "walk", fail_selected)

    findings = architecture_findings(tmp_path)

    assert sum(
        item["rule_id"] == "VR-KP-019"
        and "unavailable architecture inventory" in item["message"]
        for item in findings
    ) == len(failed_packages)


def test_architecture_check_rejects_nested_symlink_directory(tmp_path: Path):
    from knowledge.check import architecture_findings

    _copy_architecture_fixture(tmp_path)
    external = tmp_path / "external"
    external.mkdir()
    (external / "rogue.py").write_text("", encoding="utf-8")
    nested = tmp_path / "scripts/knowledge/nested"
    nested.symlink_to(external, target_is_directory=True)

    findings = architecture_findings(tmp_path)

    assert any(
        item["rule_id"] == "VR-KP-019"
        and "non-regular architecture inventory" in item["message"]
        and Path(item["path"]) == nested
        for item in findings
    )


def test_architecture_check_reports_entrypoint_stat_error(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
):
    from knowledge.check import architecture_findings

    _copy_architecture_fixture(tmp_path)
    entrypoint = tmp_path / "scripts/wiki_ingest.py"
    original = Path.lstat

    def fail_selected(path: Path):
        if path == entrypoint:
            raise OSError("fixture stat failure")
        return original(path)

    monkeypatch.setattr(Path, "lstat", fail_selected)

    findings = architecture_findings(tmp_path)

    assert any(
        item["rule_id"] == "VR-KP-019"
        and "unavailable architecture inventory" in item["message"]
        for item in findings
    )


@pytest.mark.parametrize("relative", ("scripts/knowledge/materialize.py", "scripts/knowledge/rogue.py"))
def test_architecture_check_rejects_symlink_sources(tmp_path: Path, relative: str):
    from knowledge.check import architecture_findings

    _copy_architecture_fixture(tmp_path)
    source = tmp_path / relative
    if source.exists():
        source.unlink()
    source.symlink_to(ROOT / "scripts/knowledge/materialize.py")

    findings = architecture_findings(tmp_path)

    assert any(
        item["rule_id"] == "VR-KP-019"
        and "non-regular architecture source" in item["message"]
        and Path(item["path"]) == source
        for item in findings
    )


def test_architecture_check_rejects_non_symlink_special_source(tmp_path: Path):
    from knowledge.check import architecture_findings

    _copy_architecture_fixture(tmp_path)
    source = tmp_path / "scripts/knowledge/materialize.py"
    source.unlink()
    source.mkdir()

    findings = architecture_findings(tmp_path)

    assert any(
        item["rule_id"] == "VR-KP-019"
        and "non-regular architecture source" in item["message"]
        and Path(item["path"]) == source
        for item in findings
    )


@pytest.mark.parametrize(
    "relative", (".", "scripts", "scripts/knowledge", "scripts/contracts")
)
def test_architecture_check_rejects_symlink_inventory_ancestors(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, relative: str
):
    import shutil

    from knowledge.check import architecture_findings

    external = tmp_path / "external"
    repo = tmp_path / "repo"
    _copy_architecture_fixture(external)
    if relative == ".":
        repo.symlink_to(external)
    elif relative == "scripts":
        repo.mkdir()
        (repo / "scripts").symlink_to(external / "scripts")
    else:
        repo.mkdir()
        (repo / "scripts").mkdir()
        package = Path(relative).name
        other = "contracts" if package == "knowledge" else "knowledge"
        (repo / relative).symlink_to(external / relative)
        shutil.copytree(external / "scripts" / other, repo / "scripts" / other)
        shutil.copy2(
            external / "scripts/wiki_ingest.py", repo / "scripts/wiki_ingest.py"
        )
    external_reads: list[Path] = []
    original = Path.read_text

    def observe_external_reads(path: Path, *args, **kwargs):
        if path.resolve().is_relative_to(external.resolve()):
            external_reads.append(path)
        return original(path, *args, **kwargs)

    monkeypatch.setattr(Path, "read_text", observe_external_reads)

    findings = architecture_findings(repo)

    assert any(
        item["rule_id"] == "VR-KP-019"
        and "non-regular architecture inventory" in item["message"]
        and Path(item["path"]) == (repo if relative == "." else repo / relative)
        for item in findings
    )
    assert external_reads == []


@pytest.mark.parametrize(
    ("relative", "statement", "local_sibling"),
    (
        ("scripts/contracts/privacy.py", "import projects.hidden_adapter\n", False),
        (
            "scripts/contracts/privacy.py",
            "from projects import hidden_adapter\n",
            False,
        ),
        ("scripts/wiki_ingest.py", "import projects.hidden_adapter\n", False),
        ("scripts/contracts/privacy.py", "import llm_config\n", True),
        ("scripts/wiki_ingest.py", "from llm_config import load\n", True),
    ),
)
def test_architecture_check_rejects_project_and_local_sibling_imports(
    tmp_path: Path, relative: str, statement: str, local_sibling: bool
):
    from knowledge.check import architecture_findings

    _copy_architecture_fixture(tmp_path)
    if local_sibling:
        (tmp_path / "scripts/llm_config.py").write_text(
            "def load():\n    return None\n", encoding="utf-8"
        )
    source = tmp_path / relative
    source.write_text(
        source.read_text(encoding="utf-8") + f"\n{statement}", encoding="utf-8"
    )

    findings = architecture_findings(tmp_path)

    assert any(
        item["rule_id"] == "VR-KP-019"
        and "forbidden repository import" in item["message"]
        and Path(item["path"]) == source
        for item in findings
    )


@pytest.mark.parametrize(
    ("relative", "statement", "target"),
    (
        ("scripts/knowledge/check.py", "import pipeline_sdk\n", "pipeline_sdk"),
        ("scripts/contracts/privacy.py", "import ingest_client\n", "ingest_client"),
        ("scripts/wiki_ingest.py", "import ytscript_tools\n", "ytscript_tools"),
    ),
)
def test_architecture_check_allows_legacy_near_prefix_external_imports(
    tmp_path: Path, relative: str, statement: str, target: str
):
    from knowledge.check import architecture_findings

    _copy_architecture_fixture(tmp_path)
    source = tmp_path / relative
    source.write_text(
        source.read_text(encoding="utf-8") + f"\n{statement}", encoding="utf-8"
    )

    findings = architecture_findings(tmp_path)

    assert not any(
        item["rule_id"] == "VR-KP-019"
        and item["message"].startswith("forbidden import edge: ")
        and item["message"].endswith(f" -> {target}")
        for item in findings
    )


@pytest.mark.parametrize(
    "target",
    (
        "ytscript",
        "ytscript.client",
        "ingest",
        "ingest.client",
        "pipeline",
        "pipeline.client",
    ),
)
def test_architecture_check_rejects_exact_legacy_module_roots(
    tmp_path: Path, target: str
):
    from knowledge.check import architecture_findings

    _copy_architecture_fixture(tmp_path)
    source = tmp_path / "scripts/wiki_ingest.py"
    source.write_text(
        source.read_text(encoding="utf-8") + f"\nimport {target}\n", encoding="utf-8"
    )

    findings = architecture_findings(tmp_path)

    assert any(
        item["rule_id"] == "VR-KP-019"
        and item["message"] == f"forbidden import edge: wiki_ingest -> {target}"
        for item in findings
    )


def test_target_dag_contract_covers_current_non_transitional_edges():
    import ast
    import re

    architecture = (ROOT / "docs" / "wiki-ingest-architecture.md").read_text(
        encoding="utf-8"
    )
    dag_block = architecture.split("목표 module DAG:", 1)[1]
    dag_block = dag_block.split("```text", 1)[1].split("```", 1)[0]
    parsed_edges = re.findall(
        r"^\s*([a-z_]+\.py)\s*->\s*([a-z_]+\.py)\s*$",
        dag_block,
        re.MULTILINE,
    )
    target_edges = set(parsed_edges)
    target_modules = {module for edge in target_edges for module in edge}

    assert len(target_modules) == 10
    assert len(parsed_edges) == 16
    assert len(target_edges) == 16
    assert ("check.py", "fs.py") in target_edges

    adjacency = {module: set() for module in target_modules}
    for source, target in target_edges:
        adjacency[source].add(target)

    visiting: set[str] = set()
    visited: set[str] = set()

    def visit(module: str) -> None:
        assert module not in visiting, f"target DAG cycle at {module}"
        if module in visited:
            return
        visiting.add(module)
        for target in adjacency[module]:
            visit(target)
        visiting.remove(module)
        visited.add(module)

    for module in target_modules:
        visit(module)

    def longest_path(module: str) -> int:
        targets = adjacency[module]
        return 0 if not targets else 1 + max(longest_path(target) for target in targets)

    assert max(longest_path(module) for module in target_modules) == 3

    module_by_path = {
        ROOT / relative: module for module, relative in ARCHITECTURE_MODULE_PATHS.items()
    }
    path_by_module = {module: path for path, module in module_by_path.items()}
    current_modules = {path.stem for path in module_by_path}
    current_edges: set[tuple[str, str]] = set()
    for path, module in module_by_path.items():
        source = f"{path.stem}.py"
        tree = ast.parse(path.read_text(encoding="utf-8"))
        for node in ast.walk(tree):
            for target in _architecture_import_targets(module, node):
                if target in path_by_module:
                    current_edges.add((source, path_by_module[target].name))

    assert ("check.py", "fs.py") in current_edges
    expected_final_edges = {
        (
            ARCHITECTURE_MODULE_PATHS[source].name,
            ARCHITECTURE_MODULE_PATHS[target].name,
        )
        for source, target in ARCHITECTURE_EXPECTED_EDGES
        if ARCHITECTURE_MODULE_PATHS[source].stem in current_modules
        and ARCHITECTURE_MODULE_PATHS[target].stem in current_modules
    }
    assert current_edges == expected_final_edges, sorted(
        current_edges.symmetric_difference(expected_final_edges)
    )
    assert current_edges == target_edges
    current_adjacency = {module: set() for module in current_modules}
    for source, target in current_edges:
        current_adjacency[Path(source).stem].add(Path(target).stem)

    def current_longest_path(module: str, visiting: set[str]) -> int:
        assert module not in visiting, f"current DAG cycle at {module}"
        next_visiting = visiting | {module}
        targets = current_adjacency[module]
        return (
            0
            if not targets
            else 1
            + max(current_longest_path(target, next_visiting) for target in targets)
        )

    assert (
        max(current_longest_path(module, set()) for module in current_modules)
        == ARCHITECTURE_MAX_EDGE_DEPTH
    )


def test_project_timestamp_boundary_is_exact_and_one_way():
    import ast

    converter = (
        ROOT
        / "projects"
        / "info-sec-engineer-practice"
        / "scripts"
        / "past_exam_converter.py"
    )
    converter_tree = ast.parse(converter.read_text(encoding="utf-8"))
    imports = set()
    for node in ast.walk(converter_tree):
        if isinstance(node, ast.Import):
            imports.update(alias.name for alias in node.names)
        elif isinstance(node, ast.ImportFrom):
            imports.update(_architecture_import_targets("past_exam_converter", node))
    assert {
        name
        for name in imports
        if name in {"contracts.privacy", "contracts.timestamps"}
    } == {
        "contracts.timestamps"
    }
    assert not any(name.startswith("knowledge.") for name in imports)

    architecture_paths = [
        ROOT / relative for relative in ARCHITECTURE_MODULE_PATHS.values()
    ]
    reverse_imports = []
    for path in architecture_paths:
        tree = ast.parse(path.read_text(encoding="utf-8"))
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                names = [alias.name for alias in node.names]
            elif isinstance(node, ast.ImportFrom):
                names = _architecture_import_targets(
                    f"knowledge.{path.stem}", node
                )
            else:
                names = []
            reverse_imports.extend(
                (path.name, name)
                for name in names
                if name.startswith("projects.") or name == "past_exam_converter"
            )
        source = path.read_text(encoding="utf-8")
        assert "past_exam_converter" not in source
    assert reverse_imports == []

    build_entry = converter.parent / "build-practice-data.py"
    combined_paths = [
        *architecture_paths,
        build_entry,
        converter,
    ]
    combined_modules = {path.stem for path in combined_paths}
    combined_edges = set()
    for path in combined_paths:
        tree = ast.parse(path.read_text(encoding="utf-8"))
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                names = [alias.name for alias in node.names]
            elif isinstance(node, ast.ImportFrom):
                package = (
                    "knowledge"
                    if path.parent.name == "knowledge"
                    else "contracts"
                    if path.parent.name == "contracts"
                    else ""
                )
                module = ".".join(part for part in (package, path.stem) if part)
                names = _architecture_import_targets(module, node)
            else:
                names = []
            for name in names:
                target = name.split(".")[-1]
                if target in combined_modules:
                    combined_edges.add((path.stem, target))
    expected_combined_edges = {
        (
            ARCHITECTURE_MODULE_PATHS[source].stem,
            ARCHITECTURE_MODULE_PATHS[target].stem,
        )
        for source, target in ARCHITECTURE_EXPECTED_EDGES
    } | {
        ("build-practice-data", "past_exam_converter"),
        ("past_exam_converter", "timestamps"),
    }
    assert combined_modules == {
        path.stem for path in ARCHITECTURE_MODULE_PATHS.values()
    } | {"build-practice-data", "past_exam_converter"}
    assert combined_edges == expected_combined_edges, sorted(
        combined_edges.symmetric_difference(expected_combined_edges)
    )
    assert ("build-practice-data", "past_exam_converter") in combined_edges
    assert ("past_exam_converter", "timestamps") in combined_edges
    assert {
        source for source, target in combined_edges if target == "past_exam_converter"
    } == {"build-practice-data"}
    adjacency = {module: set() for module in combined_modules}
    for source, target in combined_edges:
        adjacency[source].add(target)

    def longest(module: str, visiting: set[str]) -> int:
        assert module not in visiting, f"combined DAG cycle at {module}"
        return (
            0
            if not adjacency[module]
            else 1
            + max(longest(target, visiting | {module}) for target in adjacency[module])
        )

    assert (
        max(longest(module, set()) for module in combined_modules)
        == ARCHITECTURE_MAX_EDGE_DEPTH
    )
    business_logic = (ROOT / "docs" / "wiki-ingest-business-logic.md").read_text(
        encoding="utf-8"
    )
    assert (
        "최종 core+contract edge set exact(10 modules·16 edges)·command-inclusive "
        "12 modules·18 edges·cycle 0·최대 dependency edge chain 3" in business_logic
    )


def test_post_migration_normative_surfaces_use_current_contract_only():
    prd = (ROOT / "docs" / "wiki-ingest-prd.md").read_text(encoding="utf-8")
    architecture = (ROOT / "docs" / "wiki-ingest-architecture.md").read_text(
        encoding="utf-8"
    )
    business_logic = (ROOT / "docs" / "wiki-ingest-business-logic.md").read_text(
        encoding="utf-8"
    )
    review = (ROOT / "docs" / "wiki-ingest-review.md").read_text(
        encoding="utf-8"
    )
    agents = (ROOT / "AGENTS.md").read_text(encoding="utf-8")
    frontmatter = (ROOT / "_meta" / "frontmatter-spec.md").read_text(
        encoding="utf-8"
    )
    page_type = (ROOT / "_meta" / "page-type-spec.md").read_text(
        encoding="utf-8"
    )
    resume = (ROOT / ".claude" / "resume_prompt.md").read_text(encoding="utf-8")
    todo = (ROOT / "todo.md").read_text(encoding="utf-8")
    removal_plan = json.loads(
        (ROOT / "reports" / "P2-T7-removal-plan.json").read_text(encoding="utf-8")
    )

    assert "10-module·15-edge" not in review
    assert "순서 9 apply: no-write removal plan" not in review
    assert "base tree에만 legacy wiki contract" not in architecture
    assert "BR-MIG-001~015 적용" not in business_logic
    assert "wiki/queries/" not in agents
    assert "global/,staging/" not in agents
    assert "사용자는 legacy `wiki/`를 검토·정정할 수 있다" not in agents
    assert "target pipeline 전환 후 canonical write" not in agents
    assert "raw/ 또는 cs/ source 파일 read" not in agents
    assert (
        "raw/authored 입력은 선행 capture로 content-addressed artifact manifest를 "
        "만든 뒤에만 이 lifecycle에 들어온다" in agents
    )
    assert "사용자가 명시한 artifact manifest와 결속된 immutable payload read" in agents
    assert (
        "사용자는 `wiki/`를 검토·정정할 수 있다. canonical write는 승인된 "
        "semantic plan을 deterministic renderer가 수행한다" in agents
    )
    assert "cs/, development/, coding-test/, lang/, tools/ = authored SoT" in agents
    assert (
        "file-back이 필요하면 해당 `wiki/domains/<domain>/`의 적합한 canonical "
        "page를 갱신" in agents
    )
    assert "knowledge.schema.json" in frontmatter
    assert "knowledge.schema.json" in page_type
    assert "WIKI-INGEST-REMAINDER — 구현 순서 9–12" not in resume
    assert "P2-T7부터 P2-T11까지" not in resume
    assert "WIKI-INGEST-REMAINDER — 구현 순서 10–12" in resume
    assert "순서 9–12는 각각의 설계 gate와 독립 commit 후보" not in resume
    assert "NFR-KP-015 exact historical evidence GAP" not in resume
    assert "next_task: P2-T9" in resume
    assert "next_task: P2-T8" not in resume
    assert "P2-T9 순서 10 독립 CI 연결" in resume
    assert "P2-T8 별도 승인" not in resume
    assert "| P2-T9 | [ ] | [구현]" in todo and "| P2-T6 | extractor/current" in todo
    assert "| P2-T7 | [x] | [검증]" in todo
    assert "verified: [[reports/P2-T7-verification]]" in todo
    assert "| P2-T8 | [x] | [운영]" in todo
    assert "verified: [[reports/P2-T8-verification]]" in todo
    assert (ROOT / "reports" / "P2-T7-verification.md").is_file()
    assert (ROOT / "reports" / "P2-T8-verification.md").is_file()
    assert removal_plan["approval_state"] == "P2-T8-closure-approved"
    assert removal_plan["p2_t8_closure"]["overlay_paths"] == [
        ".claude/resume_prompt.md",
        "docs/wiki-ingest-architecture.md",
        "docs/wiki-ingest-prd.md",
        "docs/wiki-ingest-review.md",
        "tests/test_knowledge_check.py",
        "todo.md",
    ]
    assert "final commit tree" in removal_plan["p2_t8_closure"][
        "self_reference_rule"
    ]
    assert "P2-T6 독립 commit은 아직 생성하지 않았으며" not in resume
    assert (
        "P2-T6 독립 commit `e4e2d5b035401fe74b0f69721f4038a4e2bff2c8`로 "
        "확정됐다" in resume
    )
    assert "P2-T8은 exact patch·base commit·target tree OID" not in resume
    assert "사용자 승인 후 migration apply" not in architecture
    assert "순서 9의 migration apply" not in architecture
    assert "순서 9 승인 적용 뒤 제거" not in prd
    assert "순서 6b와 9의 전환 적용은 각각 별도 승인으로 수행했다" not in prd
    assert "현재 모듈(순서 9 완료 후)" not in architecture
    assert "순서 6 전환 engine과 순서 9 legacy surface는 target runtime에서 제거" in architecture
    assert "표의 선행 게이트만 의존성을 정의" in architecture
    assert "순서 9는 승인된 no-write candidate 재검증 중" not in architecture
    assert "Darwin/Linux directory exchange primitive" not in architecture
    assert "atomic leaf exchange·no-replace path rename" in architecture
    assert (
        "Git status를 보존해 wiki 삭제·이동은 현재 `WIKI_DIR` canonical 검사로 "
        "수렴" in business_logic
    )
    assert "project boundary AST test" in business_logic
    assert "순서 9: 해소 — 승인된 migration apply" not in review
    assert "순서 9: 해소 —" in review
    assert "target state 기준 구현 순서 1–9가 반영됐다" in review
    assert "다음 진입 gate: 순서 10" in review
    assert "## 7. P2-T6 historical 5계층 snapshot" in review
    assert "live target 270 passed" not in review
    assert "| Global migration safety |" not in business_logic
    assert "historical evidence이며 현재 완료 술어가 아니다" in business_logic
    assert (
        "structure-rule scope/depth·wiki path·log·backlink·provenance legacy "
        "surface | 해소 — 순서 9 target state" in review
    )


def test_taxonomy_supersede_keeps_frontmatter_field_ownership_in_schema():
    taxonomy = (ROOT / "_meta" / "taxonomy.md").read_text(encoding="utf-8")

    assert "`alias:` 필드 추가 (frontmatter + taxonomy.md 양쪽" not in taxonomy
    assert "taxonomy.md canonical 항목의 `(alias: ...)` 갱신" in taxonomy
    assert "page frontmatter `tags:`는 canonical만 저장" in taxonomy


def test_page_apply_representative_semantic_path_contract():
    import ast

    source_paths = {
        "wiki_ingest": ROOT / "scripts" / "wiki_ingest.py",
        "documents": ROOT / "scripts" / "knowledge" / "documents.py",
        "check": ROOT / "scripts" / "knowledge" / "check.py",
        "schema": ROOT / "scripts" / "knowledge" / "schema.py",
    }
    functions = {}
    for module, path in source_paths.items():
        tree = ast.parse(path.read_text(encoding="utf-8"))
        functions.update(
            {
                (module, node.name): node
                for node in tree.body
                if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef))
            }
        )

    class DirectCallVisitor(ast.NodeVisitor):
        def __init__(self):
            self.calls = []

        def visit_Call(self, node):
            self.calls.append(node)
            self.generic_visit(node)

        def visit_FunctionDef(self, node):
            return None

        def visit_AsyncFunctionDef(self, node):
            return None

        def visit_Lambda(self, node):
            return None

        def visit_ClassDef(self, node):
            return None

    def direct_calls(function):
        visitor = DirectCallVisitor()
        for statement in function.body:
            visitor.visit(statement)
        return visitor.calls

    expected_path = (
        ("wiki_ingest", "main"),
        ("wiki_ingest", "_apply_page_plan"),
        ("documents", "apply_page_write_plan"),
        ("documents", "_apply_page_write_plan_unlocked"),
        ("wiki_ingest", "_check_page_candidate"),
        ("check", "check_target"),
        ("schema", "parse_markdown"),
        ("schema", "_parse_table"),
        ("schema", "_split_table_row"),
    )
    assert len(expected_path) == 9
    assert len(expected_path) - 1 == 8

    direct_edges = (
        (expected_path[0], expected_path[1]),
        (expected_path[1], expected_path[2]),
        (expected_path[2], expected_path[3]),
        (expected_path[4], expected_path[5]),
        (expected_path[5], expected_path[6]),
        (expected_path[6], expected_path[7]),
        (expected_path[7], expected_path[8]),
    )
    for source, target in direct_edges:
        called_names = {
            call.func.id
            for call in direct_calls(functions[source])
            if isinstance(call.func, ast.Name)
        }
        assert target[1] in called_names, f"missing representative edge: {source} -> {target}"

    apply_calls = [
        call
        for call in direct_calls(functions[("wiki_ingest", "_apply_page_plan")])
        if isinstance(call.func, ast.Name) and call.func.id == "apply_page_write_plan"
    ]
    assert len(apply_calls) == 1
    callback_bindings = [
        keyword.value
        for keyword in apply_calls[0].keywords
        if keyword.arg == "candidate_check"
    ]
    assert len(callback_bindings) == 1
    assert isinstance(callback_bindings[0], ast.Name)
    assert callback_bindings[0].id == "_check_page_candidate"

    callback_calls = {
        call.func.id
        for call in direct_calls(
            functions[("documents", "_apply_page_write_plan_unlocked")]
        )
        if isinstance(call.func, ast.Name)
    }
    assert "candidate_check" in callback_calls

    architecture = (ROOT / "docs" / "wiki-ingest-architecture.md").read_text(
        encoding="utf-8"
    )
    assert "함수 9개 직렬(= edge 8)" in architecture
    assert "Python callable 전체를 재해석하는 별도 분석기는 두지 않으며" in architecture
    assert "전체 repository call graph의 exact maximum을 보장하지 않는다" in architecture


def test_corrupt_evidence_is_rejected():
    temporary, repo, target, manifest = _setup()
    try:
        _write_concept(target, "valid-concept", manifest)
        descriptor = json.loads((repo / manifest).read_text(encoding="utf-8"))
        (repo / manifest).parent.joinpath(descriptor["payload"]).write_bytes(b"corrupt")
        result = check_target(target, repo_root=repo)
        assert any(item["rule_id"] == "VR-KP-009" for item in result.findings)
    finally:
        temporary.cleanup()


def test_corrupt_normalized_content_is_rejected():
    temporary, repo, target, manifest = _setup()
    try:
        _write_concept(target, "valid-concept", manifest)
        descriptor = json.loads((repo / manifest).read_text(encoding="utf-8"))
        (repo / manifest).parent.joinpath(descriptor["content"]["path"]).write_bytes(
            b"corrupt"
        )
        result = check_target(target, repo_root=repo)
        assert any(item["rule_id"] == "VR-KP-009" for item in result.findings)
    finally:
        temporary.cleanup()


def test_changed_mode_rejects_path_outside_target():
    temporary, repo, target, manifest = _setup()
    try:
        _write_concept(target, "valid-concept", manifest)
        outside = repo / "outside.md"
        outside.write_text("outside", encoding="utf-8")
        try:
            check_target(
                target, repo_root=repo, mode="changed", changed_paths=[outside]
            )
        except ValueError as exc:
            assert "under target root" in str(exc)
        else:
            raise AssertionError("outside changed path accepted")
    finally:
        temporary.cleanup()


def test_changed_mode_detects_broken_inbound_link_after_deletion():
    temporary, repo, target, manifest = _setup()
    try:
        deleted = _write_concept(target, "deleted-page", manifest)
        _write_concept(
            target,
            "inbound-page",
            manifest,
            "| broader | [[deleted-page]] | direct inbound edge |",
        )
        deleted.unlink()
        result = check_target(
            target,
            repo_root=repo,
            mode="changed",
            changed_paths=[deleted],
        )
        assert any(
            item["rule_id"] == "VR-KP-008" and Path(item["path"]).stem == "inbound-page"
            for item in result.findings
        )
    finally:
        temporary.cleanup()


def test_rule_coverage_fails_closed_for_missing_and_unimplemented_rule():
    registry = dict(RULE_REGISTRY)
    del registry["VR-KP-011"]
    registry["VR-KP-012"] = ("active", "unknown-check")
    findings = rule_coverage_findings(registry)
    assert {finding["subject_id"] for finding in findings} == {"VR-KP-011", "VR-KP-012"}


def test_contract_checker_rejects_pin_digest_drift():
    import shutil

    with tempfile.TemporaryDirectory() as directory:
        repo = Path(directory)
        shutil.copytree(ROOT / "_meta" / "contracts", repo / "_meta" / "contracts")
        fixture_root = repo / "tests" / "fixtures" / "contracts"
        fixture_root.mkdir(parents=True)
        shutil.copy(TRANSCRIPT, fixture_root / TRANSCRIPT.name)
        pin = repo / "_meta" / "contracts" / "canonical-transcript-v1.pin.json"
        data = json.loads(pin.read_text(encoding="utf-8"))
        data["fixture_sha256"] = "0" * 64
        pin.write_text(json.dumps(data), encoding="utf-8")
        findings = contract_findings(repo)
        assert len(findings) == 1
        assert findings[0]["rule_id"] == "VR-KP-001"


def main() -> int:
    tests = [
        value for name, value in sorted(globals().items()) if name.startswith("test_")
    ]
    failed = 0
    for test in tests:
        try:
            test()
            print(f"PASS {test.__name__}")
        except Exception as exc:
            failed += 1
            print(f"FAIL {test.__name__}: {exc}")
    print(f"\n--- {len(tests) - failed} passed, {failed} failed / {len(tests)} ---")
    return int(bool(failed))


if __name__ == "__main__":
    sys.exit(main())
